# Generated by Django 3.2.9 on 2021-11-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reliability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posting.reliability'),
        ),
    ]
